name: getx_pattern_starter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.4
  image_picker: 0.8.6
  sp_util: 2.0.3
  material_design_icons_flutter: 6.0.7096
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  flutter_slidable: ^3.0.0
  dotted_border: ^2.0.0+3
  cached_network_image: ^3.2.3
  firebase_core: 2.15.1
  cloud_firestore: 4.9.1
  firebase_auth: 4.9.0
  firebase_storage: ^11.2.6
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  google_fonts: 5.1.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.63.0
  file_picker: ^5.5.0
  chewie: ^1.7.1
  video_player: ^2.7.1
  syncfusion_flutter_pdfviewer: ^23.1.36

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
