// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApuzX2z0mjliQEYIBeKdXwd8czurXrY6s',
    appId: '1:884830554822:web:f89cd671f490461b5de5c7',
    messagingSenderId: '884830554822',
    projectId: 'retako-50afd',
    authDomain: 'retako-50afd.firebaseapp.com',
    storageBucket: 'retako-50afd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYoki8YVjfusp7fWLybTk8tRsytG5Lk8',
    appId: '1:884830554822:android:1eb0c198c69204595de5c7',
    messagingSenderId: '884830554822',
    projectId: 'retako-50afd',
    storageBucket: 'retako-50afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-WMLFpTR32dc6hPXU-WgAqIESIyjl-ec',
    appId: '1:884830554822:ios:7503a0cfcec26bc05de5c7',
    messagingSenderId: '884830554822',
    projectId: 'retako-50afd',
    storageBucket: 'retako-50afd.appspot.com',
    iosBundleId: 'retako.management.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-WMLFpTR32dc6hPXU-WgAqIESIyjl-ec',
    appId: '1:884830554822:ios:7503a0cfcec26bc05de5c7',
    messagingSenderId: '884830554822',
    projectId: 'retako-50afd',
    storageBucket: 'retako-50afd.appspot.com',
    iosBundleId: 'retako.management.com',
  );
}
